### ISSUE TITLE
VST2 latency not reported unless plugin GUI is opened

### ISSUE THREAD

**Issue by dlCdS** [iPlug2/iPlug2#682] opened 2021-01-20 10:26 UTC
Bug description:
Definition of PLUG_LATENCY to a value > 0 is not reported when loaded from a saved DAW session - (Ableton in my case)
Might by related to #447 

**To Reproduce**
Create a Plug_Effect from template:
   * PLUG_LATENCY > 0 
   * copy input to output 
   * build it as VST2

Create a DAW session and add the VST2 : the latency is correctly handled
Save the session, close it, reloaded it : the latency is not handled by the DAW
Open the GUI of the VST : the latency is corrected

Correction proposed in #448 does not correct this bug
Adding SetLatency in constructor or processBlock does not correct this bug

**Expected behaviour**
Latency should be handled when plugin is instantiated

**IMPORTANT DETAILS**
VST2
Windows

**Comment by TBProAudio** [comment] 2021-01-20 10:57
Well, doing correct latency reporting is the most challenging task for advanced plugins.
In fact every DAW does it differently, even across different plugin formats.

In short:
there are 4 locations where you can report the plugin latency to the DAW:
OnParamChange()
ProcessBlock()
OnIdle()
OnReset()

Most DAWs like Reaper or Cubase accept latency report in OnIdle().
Ableton accepts latency reports in ProcessBlock() and OnReset() (VST2/VST3, not AU).

I hope this helps.

**Comment by AlexHarker** [comment] 2021-04-02 14:05
I cannot reproduce this using Ableton 10 on Mac. The plug-in latency is reported on construction as I believe it should be, so it's not 100% clear to me that there is any bug here - can you reproduce in any other DAWs except Ableton?

**Comment by TBProAudio** [comment] 2021-04-02 14:23
Correct, initial PDC is reported on construction.
But if the plugin needs to change PDC the reporting is different from DAW to DAW and from format to format.
e.g. Ableton:
accepts PDC reporting in ProcessBlock for VST2/VST3 only. AU should report in OnIdle.

**Comment by dlCdS** [comment] 2021-04-02 14:38
Thanks for your answers, I did not have the time to investigate this topic recently
As far as I remember I tried using "SetLatency(PLUG_LATENCY);" in many places in my code, including ProcessBlock and OnIdle

I plan to create an example with a basic IPlugEffect so I can share the minimal code required

**Comment by dlCdS** [comment] 2021-04-02 14:41
I precise that I don't need to change latency dynamically but only have correct reporting when loading a session containing my plugin

**Comment by AlexHarker** [comment] 2021-04-02 14:54
@TBProAudio  - my comments address the original issue here, and not the dynamic situation. 

@dlCdS - I was unable to reproduce on ableton live on Mac, and hence I'm wondering if this is an iplug2 issue or an issue with Live on windows (which wouldn't be unknown). Further testing to figure out if it affects more than one DAW on more than one platform would be handy.

**Comment by TBProAudio** [comment] 2021-04-02 15:11
Ah, i see :-) Sorry for spamming this topic ...

**Comment by dlCdS** [comment] 2021-04-03 18:03
Hi,

I investigated a little more on my plugin and it appears that I misanalysed the point in first place

I have some curve in my UI that I need to update at each cycle so I use "GetUI()->SetAllControlsDirty();" in my processblock function
I discovered that using this function while the UI is not opened make the plugin bypass the whole processblock function

For instance if you code

void IPlugEffect::ProcessBlock(sample** inputs, sample** outputs, int nFrames)
{
  const int nChans = NOutChansConnected();
  const double sampleRate = GetSampleRate();
  GetUI()->SetAllControlsDirty();

 for (int s = 0; s < nFrames; s++)
      for (int chan = 0; chan < nChans; chan++) 
        outputs[chan][s] = 0.5 * inputs[chan][s];
}

You should see that the volume is half the input if and only if the UI is opened.. I don't know if this is the expected behaviour

I think this issue can be closed and maybe another one should be opened to track this ?

**Comment by AlexHarker** [comment] 2021-04-03 18:41
You are not advised to operate on your GUI directly from the ProcessBlock() method. You are advised to use a messaging system to communicate between threads as with a control like IVScopeControl.

If you access the GUI without checking if it exists you will get undefined behaviour (I'm surprised it doesn't crash), so the code above is not safe.

I'm closing this but I don't see a clear issue here to investigate - my advice is to move to a messaging system (getting help with that on discourse or slack if needed) and then if you still think there is an issue please feel free to open a new one with a set of reproducible steps.

**Closed by AlexHarker** 2021-04-03 18:41 UTC
