### ISSUE TITLE
IGraphicsCairo plugin crashes on resize

### ISSUE THREAD

**Issue by dmsplugins** [iPlug2/iPlug2#558] opened 2020-06-21 02:36 UTC
When resizing, closing plugin window, or removing a plugin built with IGraphicsCairo, the plugin and host crashes.
Building on Mac xcode10 with  IPlug2 current as of yesterday and with dependencies current as of about a week ago.
When debugging,  xcode breaks in IGraphicsCairo:UpdateCairoContext() at cairo_destroy(mcontext) with....
Assertion failed: (s->stack->next !=NULL), function CGGStackRestore, file /BuildRoot/Library/Caches/com.apple
.xbs/Source/CoreGraphics-1265.10/CoreGraphics/Context/CGGStack.c, line 77.
This only just started happening after recently updating dependencies and bringing my local repo up to date.

**Comment by olilarkin** [comment] 2020-06-21 17:23
duplicate of #245

**Closed by olilarkin** 2020-06-21 17:23 UTC
