### ISSUE TITLE
VST2/3 crashes DDMF Plugindoctor on SetHost

### ISSUE THREAD

**Issue by johannesmenzel** [iPlug2/iPlug2#109] opened 2019-01-19 11:38 UTC
I can't determine when exactly this occured, but since few days plugins don't load in Plugindoctor (win-x64, VST2/3). Debug mode shows it fails the assert, I guess it was in IPlugAPIBase::SetHost kHost = kHostUnInit. In Reaper the same binary works fine.

**Comment by AlexHarker** [comment] 2019-01-19 13:07
I made some changes to hosts a few days ago which move where the testing for the host happens.

Part of the logic change is to try and make sure the SetHost gets called once and once only. The assert in SetHost fails if this isn't the case.

I'll investigate.

**Comment by johannesmenzel** [comment] 2019-01-19 13:21
Oh, I'll check one thing when I'm home. Possibly I missed changing Plugin ID after porting from WDL-OL to IPlug2. May be that it's conflicting with Plugindoctors state restore methods when both plugins are listed in its manager.

**Comment by AlexHarker** [comment] 2019-01-19 14:37
Yes - those changes were in the last few days, so that would make sense. I have probably assumed that some things only get called once, and those assumptions may not be safe, so I'll try to reproduce.

**Comment by AlexHarker** [comment] 2019-01-19 14:55
Thanks - I could reproduce on Mac and I have (I believe) fixed it in 

49cd63802be2c675b24ac94565856b4b1631d58a

If you can confirm then I will close the issue. I assumed that init/open would be called once only which is not the case. This change only sets the host the first time through.

**Comment by johannesmenzel** [comment] 2019-01-19 23:12
Can confirm that this assert doesn't show up anymore. Plugindoctor still crashes anyway.

**Comment by johannesmenzel** [comment] 2019-01-19 23:30
Do you have the patience to get that newbee level? First I have to get Plugin Doctor debugging here. Can take a little time.

**Comment by johannesmenzel** [comment] 2019-01-19 23:32
Te problem is Plugindoctor crashes on loading the plugin, so I don't know how to attach the process.

**Comment by AlexHarker** [comment] 2019-01-19 23:33
Load plugin doctor and attach using Visual Studio. Then open the plugin.

**Comment by johannesmenzel** [comment] 2019-01-19 23:39
Sorry, I literally meant newbee level. I switched vst-3 targets debuggings properties ro Attach process (yes) and command to my PluginDoctors binary... But how can I attach the process, if the plugins not loaded?

**Comment by AlexHarker** [comment] 2019-01-19 23:57
In the Debug menu you will find "Attach to Process..." From here you can attach to anything running on your computer.

In the meantime I've taken a look and here it looks like NanoVG on windows is still broken. If I build with Cairo for graphics then all is fine. I'll let oli know about NanoVG as it's in the setup stuff that I've not spent any time on. I'm closing this issue, as if that is the case then it is not plugin doctor specific.

**Comment by AlexHarker** [comment] 2019-01-19 23:59
Actually it would still be good to confirm at your end what the crash is, so rather than being hasty I've reopened.

**Comment by johannesmenzel** [comment] 2019-01-19 23:59
Ok, I think I found my bug myself. The reason was I didn't figure out how to get a custom buffer of size nFrames working, so I made some of size 1024, which Plugindoctor supersedes. The error occured in my overriden IVMeterBallistics class. thanks, can be closed

**Comment by AlexHarker** [comment] 2019-01-20 00:00
Great - glad to hear it!

**Closed by AlexHarker** 2019-01-20 00:00 UTC

**Comment by johannesmenzel** [comment] 2019-11-04 10:20
Can I just rewarm that issue? Currently vst3 binaries are crashing Plugin Doctor with following message:

```
The thread 0x3444 has exited with code 0 (0x0).
Exception thrown at 0x00007FFAE8CD12DE (vcruntime140.dll) in PluginDoctor64.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
The program '[11908] PluginDoctor64.exe' has exited with code 0 (0x0).
```

Vst2 works here, as well as both vst2/3 compile and run fine in Reaper as well as the standalone does.

Greetings, Hannes

**Comment by TBProAudio** [comment] 2019-11-19 17:35
I tried to nail it down (PD 1.2.5), no real luck so far, as the crash happens inside PD. But I found out that processblock is called with channel count 0 on input/output. Could this cause problems somewhere?
BTW IPLUG1 VST3 seems to work...

**Comment by johannesmenzel** [comment] 2019-11-19 18:03
Sounds interesting. The last time I had problems with PD it was because PD used very high values of buffer frames. But that last time it was my own fault because I implemented a custom buffer with maximum lenght of 1024 samples

**Comment by johannesmenzel** [comment] 2019-11-19 18:14
I'm not really into it. But my guess is that it has maybe something to do with these VST3 IO channel busses, which do not work by now.
