### ISSUE TITLE
Issue with GL3 graphics on Mac

### ISSUE THREAD

**Issue by SKyzZz** [iPlug2/iPlug2#613] opened 2020-09-03 11:19 UTC
**CHECK**
Issue

**Describe the bug**
https://iplug2.discourse.group/t/problems-with-distribution/203/4

**To Reproduce**
Compile the project. Sign the artifact and the installation package. Install on a fresh machine. Open in any DAWs

**Expected behaviour**
Correctly working plugin

**IMPORTANT DETAILS**
VST2, VST3, AUv2, 
macOS Catalina
IGRAPHICS_SKIA IGRAPHICS_GL3 IGRAPHICS_VSYNC

**Additional context**
Crash - 501 from all DAWs

**Comment by olilarkin** [comment] 2020-09-03 16:45
There is nothing here that i can reproduce and not enough info in the issue/forum thread. IGRAPHICS_SKIA IGRAPHICS_GL3 IGRAPHICS_VSYNC is working here. Do the examples crash or just your project?

**Comment by SKyzZz** [comment] 2020-09-03 17:32
To Reproduce

1. Set GRAPHICS_SKIA IGRAPHICS_GL3 IGRAPHICS_VSYNC on MAC any project
2. Compile the project. 
3. Sign the artifact and the installation package. 
4. Install on a fresh machine. 
5. Open plugin in any DAWs (LP X, Cubase 10, Reaper and etc.)

I'll make a couple of examples and test this specifically for the investigation.

**Comment by AlexHarker** [comment] 2020-09-03 17:34
I don't think the moving to another machine has anything to do with it - I think the issue is GL3 with skia on Catalina loading bitmaps (possibly on specific hardware) - or possibly GL3 on Catalina just doesn't work?

**Comment by SKyzZz** [comment] 2020-09-03 17:38
Then the counter-question is whether it will be a load on the processor, if we switched to the processor graphics and then, we will need to understand how to be with Apple Silicon.

**Comment by olilarkin** [comment] 2020-09-03 17:44
GL3 working on catalina here. Deleting a @2x png from iplugcontrols example, so it rescales @1x version, working too

**Comment by AlexHarker** [comment] 2020-09-03 20:28
OK - @SKyzZz - are you able to share the project that crashes so we can test directly with that code?

**Comment by SKyzZz** [comment] 2020-09-03 21:29
> OK - @SKyzZz - are you able to share the project that crashes so we can test directly with that code?

Unfortunately NO, Sorry(

**Comment by AlexHarker** [comment] 2020-09-03 23:39
We are probably still missing something then about what is happening here. If you can make a small example project we might be able to investigate more effectively. It could be related to a specific bitmap, or the specific machine you are testing on.

**Closed** 2020-09-28 10:56 UTC
