### ISSUE TITLE
CLAP: Bug when using Reaper FX oversampling

### ISSUE THREAD

**Issue by heebje** [iPlug2/iPlug2#895] opened 2022-09-11 12:30 UTC
I seem to have come across a strange bug in iPlug2-clap, with strange comb filtering happening when using Reaper's FX oversampling feature. The comb filtering is even different between L and R channels. The comb filtering frequency seems to be related to sample rate and buffer size (e.g. 48kHz / buffer 256 => 48000/256 = 187.5 Hz notch, as well as odd multiples of that frequency).

Situation:

Windows 10, 64-bit, everything up to date;
Reaper latest dev build: v6.67+dev0908;
iPlug2-clap, CLAP_SDK, CLAP_HELPERS, all updated to the very latest versions;
Reaper set to 48k (but this is irrelevant, as the same bug occurs on other sampling rates as well).

To reproduce the bug:

* Duplicate IPlugEffect;
* Compile CLAP version;
* Run in Reaper;
* Surround with Bertom EQ Analyzer instances (free), or any other frequency analysing tool;
* With no FX oversampling enabled in Reaper, everything works fine, the frequency response is a straight line;
* With any of Reaper’s FX oversampling settings enabled (make sure to hit Reaper's play button to activate o.s.), and the plugin's gain set to less than 100%, the plugin starts comb filtering, with the comb filtering effect different between left and right channels.
* Switching Reaper’s FX oversampling off (make sure to hit Reaper's play button to deactivate o.s.) makes the comb filtering go away again;
* Testing another CLAP plugin, such as e.g. the Surge effect plugin, does not show this problem, so that excludes Reaper as the source of the bug.
* Testing VST3 instead of CLAP shows no problem, so the problem is limited to CLAP only.

Expected behaviour:

* No comb filtering, straight EQ curve, as is the case in VST3.

![SmolPlugg-001](https://user-images.githubusercontent.com/16598068/189527631-8089a2bc-20aa-45ed-9a8f-b71ae8366bff.gif)

**Comment by olilarkin** [comment] 2022-09-11 12:51
That would seem like a reaper bug?

**Comment by AlexHarker** [comment] 2022-09-11 13:03
I will investigate. If it happens in CLAP but not VST3 it might be a either REAPER's CLAP implementation or IPlug2's CLAP.

FWIW - some other aspects of REAPER's CLAP implementation are not yet complete from the testing I've done in REAPER (such as timing information), so it's quite hard to differentiate easily. Even Bitwig does not support all CLAP extensions at the moment...

**Comment by AlexHarker** [comment] 2022-09-11 13:05
Although the obvious things to check are

- when you instantiate with oversampling what SR and block size do you get in IPlug2?

It they are wrong then it's likely not our code that is at fault.

**Comment by heebje** [comment] 2022-09-11 13:10
The reported sample rate (GetSampelRate()) and buffer size (nFrames parameter in ProcessBlock) are indeed **correct** every time (e.g. 48kHz / 256 buffer becomes => 96kHz / 512 buffer with 2x oversampling, => 192kHz / 1024 buffer with 4x oversampling, etc).
I checked this in OnReset() and ProcessBlock(): all correct, it seems.

The bug does **not** appear when e.g. using the Surge effect in CLAP format (https://surge-synthesizer.github.io/), so that _might_ indicate that Reaper is not at fault.

**Comment by AlexHarker** [comment] 2022-09-11 16:14
Thanks - that's useful to know and would seem to suggest that this isn't a REAPER bug. Surge doesn't look like it uses clap helpers so that is another possible source of issues. I'll try this shortly and see if I can get anywhere.

**Comment by AlexHarker** [comment] 2022-09-11 17:44
As an update:

1 - I can reproduce. I also get an issue with chain oversampling.
2 - If I switch up to 16x oversampling and back to 2x I don't get an issue with the results
3 - I have had one crash with this that looks like a buffer overrun

Still no clear issue in iPlug2

**Comment by AlexHarker** [comment] 2022-09-11 17:48
OK - if I oversample the chain by 16x I get a crash every time to do with malloc. If I run in the debugger with malloc guards and scribble then the crash moves into REAPER CLAP hosting code (whether oversampling the chain or the individual effect). So it actually looks highly likely to me that there is an issue in the REAPER implementation for CLAP.

**Comment by heebje** [comment] 2022-09-11 20:24
Hmmm...
Dom (My friend Dominic McSweeney) noticed that, when going back **down** in oversampling rate, the problem disappears, like you said, and I could confirm that.
So it's only when changing to a **higher** rate, and disappears when changing to a lower rate.
Very strange.

**Comment by heebje** [comment] 2022-09-11 20:25
If the issue were to be with Reaper's implementation of CLAP, how can Surge's effect plugin work correctly?

**Comment by heebje** [comment] 2022-09-11 21:32
Here are some other plugins that do **not** have the issue...
They are written in Rust.
https://nightly.link/robbert-vdh/nih-plug/workflows/build/master

**Comment by AlexHarker** [comment] 2022-09-11 21:54
> If the issue were to be with Reaper's implementation of CLAP, how can Surge's effect plugin work correctly?

Very hard to know without going through all the source code (surge's, ours, and maybe even reaper's which I can't access) in detail, but the way that plugs deal with IO buffers might be different, as well as the ordering of access to samples. It's also possible that the surge plugin allows buffer reuse (which our implementation currently does not, as I didn't yet have a chance to look the implications of that) OR it may request or prefer 32 bit signals etc. There are quite a few options within the CLAP spec, so it's not simply a case that these are *definitely* equivalent things to compare.

Right now what we know is that REAPER's oversampling implementation for CLAP can lead to memory stamping in their code which seems like a definite bug - and also that we can get correct behaviour if we back down the oversampling, suggesting that whatever is funky is at the REAPER end - once the obvious bugs are sorted I'll test again and we'll see where we are at. Don't worry, I'll leave the issue until its sorted (at both ends if necessary) ;-)

**Comment by AlexHarker** [comment] 2022-09-11 21:56
(Thanks both for updates and investigations - definitely be good to have this fixed). I'll try to look at the time info stuff for REAPER in the next build and see if that's fixed up or if we can point out to them where things looked odd.

**Comment by heebje** [comment] 2022-09-11 22:51
I'll keep on updating and testing as well, and I'll report here any new findings I might come across :)

**Comment by AlexHarker** [comment] 2022-09-11 22:57
Linking here to the cockos forum thread so it's easily to see the state of the discussion there (where I'm also posting)

https://forum.cockos.com/showthread.php?p=2595236

**Comment by heebje** [comment] 2022-09-11 23:11
Eternally grateful for all the hard work everyone is doing, and so incredibly swiftly.
Seriously impressed by all involved.
Thank you.

**Comment by heebje** [comment] 2022-09-12 19:09
Can confirm; audio is being processed correctly now :) 
The reported CPU usage (not actual usage) seems off, but that's a Reaper issue, which I have reported on the Reaper forum.
If others agree, I guess this issue can be closed :)

**Comment by AlexHarker** [comment] 2022-09-12 20:24
Confirmed here also - closing...

**Closed by AlexHarker** 2022-09-12 20:24 UTC
