### ISSUE TITLE
Resizing issue

### ISSUE THREAD

**Issue by analogobsession** [iPlug2/iPlug2#423] opened 2020-01-19 19:57 UTC
Hi,

I'm using .png files as GUI elements. Vertical strips. 61 frames.

Just duplicated IPlugEffect and imported my .png files. Everything is great but resizing is buggy.

There is no issue with 1:1 view but if you make it smaller or bigger, it shows current frame with next frame's first pixel line.

Here is video to show issue clear. As you can see, there is a black line under knob. Actually, it's line of frame's up pixel line.

[https://streamable.com/u74u3](url)

**Comment by analogobsession** [comment] 2020-01-19 22:54
Also, GUI returning default view after resizing, closing GUI and re-opening GUI. So, it doesn't stay at resized GUI.

**Comment by olilarkin** [comment] 2020-01-22 11:42
Many things about this issue are a bit vague so i am closing it. I have created an issue template to guide people on how to create issues. please create a new issue with all the details. Regarding your second post which is about something different, it's not a bug, you have to implement that yourself. we can discuss on slack

**Closed by olilarkin** 2020-01-22 11:42 UTC
