### ISSUE TITLE
Crash: IPlugEffect, OSX, CAIRO, resize

### ISSUE THREAD

**Issue by TBProAudio** [iPlug2/iPlug2#647] opened 2020-11-05 06:57 UTC
Describe the bug
IPlugEffect compiled under OSX with CAIRO crashes during resizing

To Reproduce
Just compile IPlugEffect app and drag resize handle.
SigAbrt in IGraphicsCairo.cpp, UpdateCairoContext() => cairo_destroy(mContext);
 
Expected behaviour
No crash. 

Screenshots
na

IMPORTANT DETAILS
No crash under Windows 10

Additional context
na

**Comment by olilarkin** [comment] 2020-11-05 09:19
duplicate of https://github.com/iPlug2/iPlug2/issues/245

**Closed by olilarkin** 2020-11-05 09:19 UTC

**Comment by TBProAudio** [comment] 2020-11-05 09:34
Sorry, just saw it :-(
