### ISSUE TITLE
IGraphicsCairo crash on resize (mojave)

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#245] opened 2019-06-26 18:05 UTC
drag corner resizer...

```
void IGraphicsCairo::UpdateCairoContext()
{
  if (mContext)
  {
    cairo_destroy(mContext);  //asserts


Assertion failed: (s->stack->next != NULL), function CGGStackRestore, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreGraphics/CoreGraphics-1260.2/CoreGraphics/Context/CGGStack.c, line 77.```

**Comment by AlexHarker** [comment] 2019-06-30 23:42
This was reported before - seems like it could be a Cairo bug though - the crash is certainly inside Cairo code.

**Comment by AlexHarker** [comment] 2019-09-21 20:09
This fix breaks Cairo layers and misbalances save/restore pairs -it's not viable. Leaving it in causes HISSTools_Granular to draw with very weird clipping and taking it out works. We need a better fix.

**Comment by AlexHarker** [comment] 2019-09-21 20:11
It *might* work to but it in UpdateCairoMainSurface() but in general it is a hack and we should find a non-hacky solution.

**Comment by AlexHarker** [comment] 2019-09-21 20:36
After investigating further we should also consider the possibility that the crash is due to a mismatch on calls from SWELL or our handling of SWELL.

I'm not on Mojave so we need a test on there with APP and a plugin - if it happens in both then probably the issue is in Cairo - if only on the APP then we need to look at SWELL

**Comment by olilarkin** [comment] 2019-09-23 11:58
didn't mean to close. reverted commit 29faa2f99e48b369f79586a944043d3019216c09

**Comment by olilarkin** [comment] 2019-09-30 18:13
new attempt. https://github.com/iPlug2/iPlug2/tree/graphics/fix_cairo_assert

**Comment by olilarkin** [comment] 2020-05-18 12:25
crash also spotted in logic when moving ui from one screen to another

**Comment by AlexHarker** [comment] 2020-07-12 10:41
I now get this crash on Cairo whenever closing the interface - not sure why that changed for me.

**Closed** 2020-11-15 23:44 UTC
Labels: bug, cairo, igraphics
