### ISSUE TITLE
SetLatency() issue with VST3 in Ableton Live - merged #731 only partial fix

### ISSUE THREAD

**Issue by rexmartin158** [iPlug2/iPlug2#772] opened 2021-07-13 18:26 UTC
**Describe the bug**
Ableton Live does not set the correct latency per SetLatency() when a VST3 plugin is constructed.

**To Reproduce**

1. Create a blank Ableton Live project
2. Insert VST3 version of plugin on any track or bus - the plugin reports 0 samples latency regardless of SetLatency() value
3. Turn the plugin off ("deactivate") - now it reports the correct latency
4. Turn the plugin on again - still reports correct latency.
5. Save the project
6. Reload the project - the plugin loads up reporting 0 latency again. If you deactivate then re-activate the plugin it will report correct latency again, but every time you reload the project it will report 0 incorrectly again until you do this.

**Expected behaviour**
Plugin should load correct SetLatency() value on initial construction (SetLatency() called in OnReset()).

**Cause of the problem**
Fix for SetLatency() merged in #731 fixes the crash on startup but does not address the latency issue.  The reason is because Ableton does not have a "componentHandler" until after MakeGraphics() is totally finished.  Ableton calls OnReset() twice during construction but neither time is "componentHandler" a valid pointer so SetLatency() is never implemented.

**Workaround**
I don't know if this can be "fixed" in iPlug code because it appears to be a flaw in Ableton.  All other DAWs I have tested enact SetLatency() immediately on the first call to OnReset().  If it can be addressed via iPlug please advise.

In the meantime, as a workaround for Ableton I have added a latency check to OnActivate() as follows:

```
void MyPlugin::OnActivate(bool state)
{
    if (state)
    {
        if (GetHost() == kHostAbletonLive)
        {
            if (GetLatency() != desiredlatency) SetLatency(desiredlatency);
        }
****

```
Ableton calls OnActivate() one more time (a third time) at the conclusion of plugin construction at which point "componentHandler" is valid and this "hack" then loads the correct latency. 

Not sure if there are any side effects of this hack but it seems to fix the problem.

**Comment by AlexHarker** [comment] 2021-12-01 01:15
Thanks for this - if you remove your hack, but edit PlugVST3.cpp to place this line:

      IPlugProcessor::SetLatency(latency);

before the two if statements -does that also work? That looks like the correct fix.

**Comment by AlexHarker** [comment] 2021-12-01 08:33
I've tested and put the fix here:

https://github.com/iPlug2/iPlug2/tree/VST3/latency

I'll merge it soon but it'd be good to have it confirmed that this removes the need for a workaround.
It looks like this method should also be overridden for the VST3 distributed build - (maybe @olilarkin can confirm if that need to happen only on the processor side or not). I'll aim to address that and merge together.

**Comment by TBProAudio** [comment] 2021-12-01 09:22
Hi Alex,

i think that this fix produces more problems than it solves.
At least in our plugins the code 

`void IPlugVST3::SetLatency(int latency)
{
  if (componentHandler)
  {
    FUnknownPtr<IComponentHandler>handler(componentHandler);
    if (handler)                                                
    {
      IPlugProcessor::SetLatency(latency);
      handler->restartComponent(kLatencyChanged);
    }
  }
}`

works perfectly.

Ableton VST3 accepts change of plugin latency in ProcessBlock without any issues.

**Comment by AlexHarker** [comment] 2021-12-01 09:51
@TBProAudio 

Can you explain how it creates issues? In all other formats IPlugProcessor::SetLatency() will be called directly. In VST3 we should also request that the component is restarted. All I've done is move the call to super so that it happens even if the component doesn't exist yet. I cannot see how that would create side effects, but if it it does I need to know what they are.

I'm happy to reconsider if you can point to an issue, but a general "this creates problems" isn't very helpful.

In case it isn't obvious, my fix is NOT the workaround suggested in the original post.

**Comment by AlexHarker** [comment] 2021-12-01 09:52
And yes - SetLatency will work in ProcessBlock with the old code - the point here is to make it work elsewhere (such as the constructor, which seems a perfectly reasonable place to set the latency).

**Comment by rexmartin158** [comment] 2021-12-01 16:52
> Hi Alex,
> 
> i think that this fix produces more problems than it solves. At least in our plugins the code
> 
> `void IPlugVST3::SetLatency(int latency) { if (componentHandler) { FUnknownPtr<IComponentHandler>handler(componentHandler); if (handler) { IPlugProcessor::SetLatency(latency); handler->restartComponent(kLatencyChanged); } } }`
> 
> works perfectly.
> 
> Ableton VST3 accepts change of plugin latency in ProcessBlock without any issues.

Curious why this works for you but not for me?  Did you change something somewhere else as well? What you show - and currently in iPlug - does not work properly in Ableton here without the workaround code posted in my OP.


> And yes - SetLatency will work in ProcessBlock with the old code - the point here is to make it work elsewhere (such as the constructor, which seems a perfectly reasonable place to set the latency).

To be clear on my OP, I am not setting latency in the constructor - I check and set it in OnReset().  Some DAWs (like Ableton) allow changing the sample rate after plugins are inserted.  Therefore, checking SR in OnReset() seems the most reliable place.

**Comment by rexmartin158** [comment] 2021-12-01 17:03
> Thanks for this - if you remove your hack, but edit PlugVST3.cpp to place this line:
> 
> line 252 IPlugProcessor::SetLatency(latency);
> 
> before the two if statements -does that also work? That looks like the correct fix.

Yes it does work here!  Ableton reports correct latency as soon as the plugin is loaded which fixes the problem I experienced in this thread.  I also tried changing the project sample rate after the plugin was loaded and the latency shown in the plugin window immediately updated.  Looks like the right fix to me.

**Comment by AlexHarker** [comment] 2021-12-01 17:22
Thanks @rexmartin158 - sorry for the mistake about exactly where, but OnReset() will be called pretty early on when the plugin is created, although not quite in a constructor.

**Comment by AlexHarker** [comment] 2021-12-01 17:29
@TBProAudio - I have some thoughts on how there might be a way to improve on this, depending on what your concerns are exactly, but you'd need to articulate them to help me see them arising in practice.

From my perspective there are two issues at play:

A - when the iplug side of things updates the latency (as reported by IPlugProcessor::GetLatency(). That should be immediate (which it was not before the fix I proposed above). Anything else is a recipe for unexpected behaviour/bugs from the plug programmer's perspective.

B - when the VST3 host is aware of the change of latency. In the fix above arguably there is the potential for what in your comments on your original fix you mentions "getting out of sync" - I consider this to be a theoretical, but likely not realworld possibility, because if the handler doesn't exist there is nothing to yet be out of sync with (and the plug plugin should at least be in sync with itself). I am unaware of another scenario in which the plugin would be in full operation and be actually out of sync.

If you can provide more info I can look into whether there is a real world issue that necessitates putting time into coding a more complex fix that separates issues A and B above. Without an example of the issue occurring in the wild then I consider the fix above to be the best state of things.

**Comment by TBProAudio** [comment] 2021-12-01 18:43
Hmm, i miss my last post regarding "out of sync". Seems to be disappeared :-)
Sure: DAW, framework and user code should be in sync. If report to DAW is not possible (component missing => IPLUG2/DAW out of sync) it should be detectable (getlatency) by the user code. Thats all.

**Comment by AlexHarker** [comment] 2021-12-01 20:00
The out of sync" is in your code here:

https://github.com/iPlug2/iPlug2/issues/731#issuecomment-815455062

I'm afraid that I don't fully follow your reply. If the component doesn't exist it means that the host has not fully constructed it yet - the component is not "missing" as in disappeared - it hasn't been made yet which means that we should store the request from the plugin programmer and it will get honoured when the plug is fully created.

The other approach to this is for you to test the branch I Lin above and give an example of where it fails to work as expected. Thanks.

**Comment by rexmartin158** [comment] 2021-12-07 17:08
@AlexHarker 

We haven't heard from @TBProAudio but I can confirm your fix [https://github.com/iPlug2/iPlug2/tree/VST3/latency](url) is working here.  Thank you.

**Comment by AlexHarker** [comment] 2021-12-09 23:23
Closed as the fix has now been merged

**Closed by AlexHarker** 2021-12-09 23:23 UTC
