### ISSUE TITLE
Black window in GarageBand 10 with IGRAPHICS_CAIRO

### ISSUE THREAD

**Issue by hor-net** [iPlug2/iPlug2#384] opened 2019-11-07 11:10 UTC
If open IPlugEffect in GarageBand I get a black window:

![image](https://user-images.githubusercontent.com/704273/68383471-04595500-0156-11ea-86aa-91b2a603d8e2.png)

If I add a second instance of the plugin the GUI is shown but as soon as I close the GUI window GarageBand crashes in line 583 of IGraphicsCairo.cpp where mContext is destroyed.

```
void IGraphicsCairo::UpdateCairoContext()
{
  if (mContext)
  {
    cairo_destroy(mContext);
    mContext = nullptr;
  }
  
  cairo_surface_t* pSurface = mLayers.empty() ? mSurface : mLayers.top()->GetAPIBitmap()->GetBitmap();

  if (pSurface)
    mContext = cairo_create(pSurface);
  
  //cairo_set_antialias(mContext, CAIRO_ANTIALIAS_FAST);
}
```

Tested with GarageBand 10 on macOS 10.14.6

NANOVG backend works fine.

**Comment by TBProAudio** [comment] 2019-11-08 06:56
Yes, i can confirm that Cairo crashes on Mac during hiding/showing the GUI.

**Comment by olilarkin** [comment] 2019-11-08 09:00
this might fix it https://github.com/iPlug2/iPlug2/tree/graphics/fix_cairo_assert

**Comment by hor-net** [comment] 2019-11-08 09:29
Here's a short clip exhibiting the issue:

https://drive.google.com/file/d/1cpxcSdVW9aTdWCTsHlkuDV2K8KVpaQmk/view?usp=sharing

**Comment by hor-net** [comment] 2019-11-08 09:40
> this might fix it https://github.com/iPlug2/iPlug2/tree/graphics/fix_cairo_assert

Just tested this branch and it seems to fix the issue in GB, i haven't tested any other DAW.

**Comment by TBProAudio** [comment] 2019-11-08 15:58
inserting this into master does the trick:
```
#ifdef OS_MAC
    CGContextSaveGState((CGContextRef)GetPlatformContext());
#endif
```
Tested VST2 in Reaper...

**Comment by AlexHarker** [comment] 2019-11-08 18:13
I don't consider this fix to be a good way to do this because somewhere there is an imbalance in save/restore pairs, and it doesn't appear to be in our code - it's possible it is in Cairo, but it doesn't appear on old systems, just new ones.

**Comment by hor-net** [comment] 2019-11-11 11:14
Consider that GB is a sandboxed application, I don't know if this makes any difference

**Comment by olilarkin** [comment] 2019-12-21 17:42
closing, duplicate issue here https://github.com/iPlug2/iPlug2/issues/245

**Closed by olilarkin** 2019-12-21 17:42 UTC
