### ISSUE TITLE
VST3 in Ableton Live 10 & 11 creates wrong Editor Window size on initial construction

### ISSUE THREAD

**Issue by rexmartin158** [iPlug2/iPlug2#769] opened 2021-06-29 05:10 UTC
**Describe the bug**
Ableton appears to be ignoring IPlugVST3::EditorResize() during plugin construction (called from MakeGraphics) creating the wrong initial plugin Editor Window size with VST3 plugins.  Plugin graphics are scaled properly but Editor Window is not, thereby creating white space around plugin (at <1.0 scales) or truncated graphics (at >1.0 scales).

**To Reproduce**
Set MakeGraphics or Resize() scale in plugin constructor to any number other than 1.0.  Launch plugin in Ableton Live. Plugin will open with Editor Window of the wrong size.  All bitmap and vector graphics are scaled properly but the plugin Editor Window itself is drawn to PLUG_HEIGHT  x  PLUG_WIDTH ignoring MakeGraphics or any other Resize() scale factor.

**Expected behaviour**
Ableton should size the plugin editor window to scaled "viewWidth, viewHeight" as executed in IPlugVST3::EditorResize() but mView->Resize() and/or SetEditorSize() are being ignored.

**IMPORTANT DETAILS**
* What plug-in format does it relate to:  only VST3 -- VST2 version works properly
* What platform does it relate to - Windows
* What IGRAPHICS_BACKEND does it relate to: tested and occurs with both NANOVG and SKIA

**Additional context**
Problem only occurs with VST3 version - VST2 works properly.  Both versions work properly in other DAWs (tested in Reaper, Cubase, Cakewalk, Tracktion).  

VS debugger shows all window size creation functions (in IPlugVST3 files) carry the correctly scaled plugin window width and height.  That scale, however, is not being applied to the Editor Window. 

This only occurs on initial plugin construction.  Subsequent UI size changes with corner resizer control works properly (Editor Window snaps to/resizes to match graphics).

This is possibly a bug in Ableton.   If known issue please advise.

**Comment by TBProAudio** [comment] 2021-06-29 14:32
Confirmed.
Call of "Steinberg::tresult PLUGIN_API getSize(Steinberg::ViewRect* pSize) override" comes very early, view width and height are not updated with current scale.

Need to see if we can provide a hack, beause it seems to be a Ableton issue ...

**Comment by rexmartin158** [comment] 2021-06-29 15:20
> Need to see if we can provide a hack, because it seems to be a Ableton issue ...

Thank you for checking and confirming.

Yes, it seems a conditional hack may be required.  I have only seen this peculiar behavior in Ableton and, even more peculiar, only in the _VST3_ version of plugin.

It appears that Ableton sizes the initial plugin Editor Window based entirely on:

#define PLUG_WIDTH
#define PLUG_HEIGHT

while completely disregarding MakeGraphics.  I have tested with all different numbers in MakeGraphics and the only thing that changes is the size of the graphics _within_ the Editor Window - no values in MakeGraphics affect the initial Editor Window size itself.

**Comment by rexmartin158** [comment] 2021-07-09 21:37
> Call of "Steinberg::tresult PLUGIN_API getSize(Steinberg::ViewRect* pSize) override" comes very early, view width and height are not updated with current scale.

I am having trouble trying to trace this - my VS2019 refuses to hit breakpoints complaining that "no symbols have been loaded" - but yet I can debug in Reaper and other DAWs with no problem (where, ironically, the plugin works properly).

Can you advise if there is a "trick" to debugging Ableton?  This is in Windows 10.

**Comment by rexmartin158** [comment] 2021-07-09 23:40
> Confirmed.
> Call of "Steinberg::tresult PLUGIN_API getSize(Steinberg::ViewRect* pSize) override" comes very early, view width and height are not updated with current scale.
> 

Running debug on plugin load also shows GetHostResizeEnabled() returns FALSE even though the plugin is set in Ableton to "Auto-Scale Plugin Window".

```
  Steinberg::tresult PLUGIN_API canResize() override
  {
    if (mOwner.HasUI() && mOwner.GetHostResizeEnabled())
    {
      return Steinberg::kResultTrue;
    }
    
    return Steinberg::kResultFalse;
  }
```

So, is this a bug in Ableton?

**Comment by AlexHarker** [comment] 2021-07-12 07:44
This sounds like#593 as you've identified. The issue is related to how Live queries the plugin and takes the initial size (before the window is made) and resizes to that *after* the internal editor resize). I have traced this in detail in the past.

I consider this to be an Ableton bug, but the way to work around it is to recall the correct plugin size prior to opening the window. If you save the correct size with your plug data dn then recall at construction you can get correct behaviour (you can see this in Surreal Machines Crack plugin, which is free and did the C++ work for). If you need a more detailed breakdown on how to do this I can try to put together an example when I have a bit more time.

I can try to get some traction with Ableton on getting them to fix the behaviour, but it may be easier for you to work around it.

**Comment by rexmartin158** [comment] 2021-07-13 01:24
Thank you for the reply and suggested workaround.

> I can try to get some traction with Ableton on getting them to fix the behaviour, but it may be easier for you to work around it.

VST3 support in Ableton is relatively new (with v10.1, ~July 2019).  IMO, either their implementation is peculiar or they still have many bugs to work out.  I have had little trouble with VST2 and AU plugins but VST3 has been constantly problematic.

**Comment by olilarkin** [comment] 2021-07-13 20:25
Here is a workaround in iPlug2 code for now...
Only tested on 200% high dpi screen, I expect it is not yet right for low-dpi

[live-vst3-highdpi.txt](https://github.com/iPlug2/iPlug2/files/6811774/live-vst3-highdpi.txt)

**Comment by TBProAudio** [comment] 2021-07-14 11:40
Thanks Oli for the example.
I took this as a base for further investigations and I think I found a solution (aka hack)

**IPlugEditorDelegate.h**
  virtual void SetScreenScale(double scale) {}
  void SetEditorInitScale(double scale) { mInitGuiScale = scale;}   // 14072021 Ableton hack
  double GetEditorInitScale() { return mInitGuiScale; }             // 14072021 Ableton hack

  int mMinWidth, mMaxWidth, mMinHeight, mMaxHeight;
  double mInitGuiScale = -1.0;              // 14072021 Ableton hack
  
**IPlugVST3.h**
 void removeAudioOutputBus(Steinberg::Vst::AudioBus* pBus)
  {
    audioOutputs.erase(std::remove(audioOutputs.begin(), audioOutputs.end(), pBus));
  }
    bool CheckAbletonGUIHack()                                                          // 14072021 TBPROAUDIO Hack for Ableton init GUI Scale                
    {
        if (GetHost() == kHostAbletonLive && !mFirstHitInLiveWin)
        {
            mFirstHitInLiveWin = true;
            return true;
        }
        return false;
    }

  ViewType* mView;
  bool mFirstHitInLiveWin = false;	                            // 14072021 TBPROAUDIO Hack for Ableton init GUI Scale
  
**IPlugVST3_View.h**
  Steinberg::tresult PLUGIN_API getSize(Steinberg::ViewRect* pSize) override
  {
    TRACE

    if ((mOwner.GetEditorInitScale() != -1.0) && mOwner.CheckAbletonGUIHack())   // 14072021 TBPROAUDIO Hack for Ableton init GUI Scale
    {
        if(mOwner.GetParam(0)->Value() != 1.0)
            return Steinberg::kResultFalse;
    }

    if (mOwner.HasUI())
    {
      *pSize = Steinberg::ViewRect(0, 0, mOwner.GetEditorWidth(), mOwner.GetEditorHeight());
      return Steinberg::kResultTrue;
    }
    else
    {
      return Steinberg::kResultFalse;
    }
  }
  
  **plugin.cpp constructor**
  ...
  	mScale = GetParam(kGUIScale)->Value();
  	SetEditorInitScale(mScale);													// 14072021 Ableton hack				
  ...

Tested under Win 10 x64, Reaper, Cubase and Ableton 11

**Comment by rexmartin158** [comment] 2021-07-14 17:31
Thank you, Oli and TB Pro for posting this.  I tried something similar with a one-time resize call "if (kHostAbleton)" that almost worked but I felt I was going too far down a custom code path with possible side effects so I stopped.

TB Pro - your code example here removes the audio output bus - why is that step necessary and where is it re-established?

**Comment by TBProAudio** [comment] 2021-07-15 04:40
Well, just add the code which is marked with "// 14072021 Ableton hack" or "// 14072021 TBPROAUDIO".
Function "Steinberg::tresult PLUGIN_API getSize" needs to be fully replaced.
The rest is just for orientation :-)

**Comment by rexmartin158** [comment] 2021-07-15 23:27
> 
> 
> Well, just add the code which is marked with "// 14072021 Ableton hack" or "// 14072021 TBPROAUDIO".
> Function "Steinberg::tresult PLUGIN_API getSize" needs to be fully replaced.
> The rest is just for orientation :-)

Got it.  Thank you.

**Comment by AlexHarker** [comment] 2022-01-14 23:33
Closing this as an exact duplicate (the other issue references this, so this info is still linking from there.

**Closed by AlexHarker** 2022-01-14 23:33 UTC
Labels: duplicate
