### ISSUE TITLE
Faust example on Windows

### ISSUE THREAD

**Issue by KuzMaxOriginal** [iPlug2/iPlug2#473] opened 2020-03-16 17:29 UTC
I'm building IPlugFaustDSP on Windows, using Visual Studio 2019. 

When linking, I'm getting the following error:

`Error	LNK2019	unresolved external symbol "class llvm_dsp_factory * __cdecl createDSPFactoryFromString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,char const * * const,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,int)" (?createDSPFactoryFromString@@YAPAVllvm_dsp_factory@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HQAPBD0AAV23@H@Z) referenced in function "public: class llvm_dsp_factory * __thiscall iplug::FaustGen::Factory::CreateFactoryFromSourceCode(void)" (?CreateFactoryFromSourceCode@Factory@FaustGen@iplug@@QAEPAVllvm_dsp_factory@@XZ)	IPlugFaustDSP-app	C:\Users\Maksim\Desktop\Development\C++\iPlug2-master\Examples\IPlugFaustDSP\projects\IPlugFaustGen.obj`

And other 2 similar, all are related to IPlugFaustGen.

I've tried define FAUST_COMPILED in config. It builds, but the result is that I'm not getting what is described in .dsp file, but instead there are 4 sliders called "Param 1, Param 2", etc. and a lot of menu options. 

What am I doing wrong?

**Comment by olilarkin** [comment] 2020-03-16 17:42
The issue there is that it is not linking faust.lib. Unfortunately currently have some issues building a reliable faust.dll on windows https://github.com/grame-cncm/faust/issues/362

there are more details here regarding using faust on windows. I suggest for now you could define FAUST_COMPILED and use faust.exe to update FaustCode.hpp 

https://github.com/iPlug2/iPlug2/blob/master/Examples/IPlugFaustDSP/README.md

NOTE: i am closing this issue, since it is a question not a bug as such, can discuss further on slack if you like

**Closed by olilarkin** 2020-03-16 17:42 UTC

**Comment by KuzMaxOriginal** [comment] 2020-03-17 04:46
But when I use FAUST_COMPILED, I'm getting not what .hpp describes. How can I apply sliders from .dsp/.hpp to the plugin?

**Comment by olilarkin** [comment] 2020-03-17 09:59
you can do something like this:

MyFaustPlugin::MyFaustPlugin(const InstanceInfo& info)
: Plugin(info, MakeConfig(kNumParams, kNumPrograms))
{
//  GetParam(kGain)->InitDouble("Gain", 100., 0., 100.0, 0.01, "%");
  
  mDSP.SetMaxChannelCount(2, 2);
  mDSP.Init();
  FaustGen::CompileCPP();
  mDSP.SetAutoRecompile(true);
  mDSP.CreateIPlugParameters(this, 0, kNumParams);
 ...
kNumParams is set in advance to >= the number of params in your faust .dsp. If not it will probably crash

**Comment by KuzMaxOriginal** [comment] 2020-03-17 11:23
Thank you for your replies. I hope you've got some more patience on newbie... ;)

How do I connect existing parameter, e. g. "Param 1" to Faust slider? So I'm creating GUI with iPlug2, but all the DSP processing goes through Faust. I see a line of your code:

`// GetParam(kGain)->InitDouble("Gain", 100., 0., 100.0, 0.01, "%");`

I suppose, there got to be a place where kGain is initialized, and it is the very "Gain" parameter, described in .dsp. But I don't see any definition of it in the code. If you give me a one, you have my gratitude.

**Comment by olilarkin** [comment] 2020-03-17 11:25
NOTE: i am closing this issue, since it is a question not a bug as such, can discuss further on slack if you like

**Comment by olilarkin** [comment] 2020-03-17 11:27
//GetParam is not used here - it is commented out.

mDSP.CreateIPlugParameters(this, 0, kNumParams);

creates iPlug params based on the faust .dsp params
