### ISSUE TITLE
processblock isnt called anymore, when (more then one) string is put into chunk after reloading plugin in bitwig.

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#449] opened 2020-02-04 13:29 UTC
setup:
bitwig v3.0.3 & v3.1.2
win10
vst3x64
Iplug version from today 04.02.2020
vst-sdk_3.6.14_build-24_2019-11-29

reproduce: 
implement serialize and unserialize state in iplugeffect and put two strings to chunk (chunk.PutStr("str1");
chunk.PutStr("str2");) in serialize state. load iplugeffect in bitwig - breaking in processblock should work. right click on iplugeffect in bitwig and deactivate and then activate again. attach debugger - processblock is not called anymore.

*config.h plug does state chunks doesnt affect this bug
*with one string added behavior seems sporadic
*issue appears to be new, so i suppose its not on bitwigs side - not sure though

![processblock-callissue(1)](https://user-images.githubusercontent.com/46456607/73748796-78f25e80-475a-11ea-92ae-4ac48fcdab97.gif)

**Comment by AlexHarker** [comment] 2021-03-27 22:44
Looking at this I'm unclear on if UnserializeState() is correctly implemented - the return value from this is relied upon in IPlugVST3State::SetState() to read the bypass value, and if it returns 0 it will read the first four characters of the string as the bypass value - thus bypassing the plugin.

I suspect, therefore, that this is not a bug in iplug2, but there isn't enough info to be 100% sure here.

**Comment by AlexHarker** [comment] 2022-01-14 23:28
@janhase88 I'm closing this - if you have further evidence (an example project) to investigate and this looks like user error.

**Closed by AlexHarker** 2022-01-14 23:28 UTC
