### ISSUE TITLE
Mac, ITextEntryControl.cpp: Minus key not recognized

### ISSUE THREAD

**Issue by TBProAudio** [iPlug2/iPlug2#707] opened 2021-03-16 06:22 UTC
Minus key of Mac(Book) keyboard (key close to enter key) is not recognized. This means the user cannot enter negative numbers. 

To Reproduce:
Use any control with input prompt, enable global mTextEntryControl by using pGraphics->AttachTextEntryControl();

Possible fix:

add 2 times

```
#if defined(OS_MAC)
            if (key.VK == kVK_INSERT)                       
            {
                stbKey = '-';
                break;
            }
#endif
```
to switch (pParam->Type()){}, kTypeInt and kTypeDouble

IMPORTANT DETAILS

    What plug-in format does it relate to - vst2/vst3/aax/au
    What platform does it relate to - Mac

**Comment by AlexHarker** [comment] 2021-03-20 12:35
I can't reproduce this issue here - my minus key picks up fine - can you give more details about your keyboard and keyboard configuration? Is this the only minus sign on your keyboard, or is it a secondary one?

**Comment by AlexHarker** [comment] 2021-03-20 12:38
I get the correct stbKey of 45 ("-") with my keyboard so there's definitely an issue with the key detection on your setup here - we'd need more details to investigate further.

**Comment by TBProAudio** [comment] 2021-03-20 14:34
Maybe it is an issue with the keyboard/locale layout/settings in IPLUG2:

I have a German layout: https://keyshorts.com/blogs/blog/37615873-how-to-identify-macbook-keyboard-localization#german
which has the "minus" key close to the right shift key.
So with German layout I get kVK_INSERT when minus is pressed...

1) The issue is Mac only
2) App works, VST2/VST2/AAX and AU not

maybe this helps.

**Comment by AlexHarker** [comment] 2021-03-20 14:50
OK - I think we are probably looking in the wrong place - would you be able to tell me what rawcode value you get for that key in MacKeyEventToVK in IGraphicsMac_view.mm (line 97 on master)? 

Is it 114? If so then some assumptions about virtual key mappings on Mac might be where the issue is.

**Comment by TBProAudio** [comment] 2021-03-20 15:21
Hmm, IGraphicsMac_view.mm breaks only with App.
Does not break with vst2.

**Comment by AlexHarker** [comment] 2021-03-20 18:31
My bad - I misread your original report - the issue here is what we are getting passed from VST2VST3 key handlers - I CAN'T see a reason why AU and AAX wouldn't work as these should go through igraphics view - can you test with audio unit?

I can now reproduce on VST2 / VST3 in reaper and we'll need to modify the key codes appropriately somewhere.

**Comment by AlexHarker** [comment] 2021-03-20 18:45
Looks like iplug::IKeyPress translateKeyMessage and effEditKeyDown / effEditKeyUp in the VST2 dispatched need some attention as they assume that a minus would be coming in as a string (it isn't).

I can't see an issue with audio unit here though (and I can't test AAX).

**Comment by AlexHarker** [comment] 2021-03-20 18:47
Need to make sure we are dealing with all of these:

https://steinbergmedia.github.io/vst3_doc/base/namespaceSteinberg.html#a9380117707cebcb5a3cd9fa8b960e22b

**Comment by AlexHarker** [comment] 2021-03-20 23:35
Oli also reports that this might be host dependent and might only happen in Reaper (it doesn't appear to be an issue in Live)

**Comment by TBProAudio** [comment] 2021-03-21 07:45
Quick test here again:

Cubase VST2/VST3 OK
Logic OK
Reaper: AU OK, VST2/VST3 NOK
PT: OK

So yes, it seems to be DAW VST2/VST3 dependent, maybe Reaper only :-(

**Comment by AlexHarker** [comment] 2021-03-21 10:42
Thanks for confirming - I think we have it located to VST2/3 key handling and in this case it is to do with what reaper is handing us for key info so we'll need to look at whether this is a reaper bug...

**Comment by TBProAudio** [comment] 2021-03-24 12:10
Latest feedback from a customer:

No minus key detection in Cakewalk/Sonar, Windows, x64 VST2/VST3, Swedish keyboard layout.
Cakewalk/Win/German layout works here.

So it seems that we need to disable TextEntryControl in our products :-(

**Comment by AlexHarker** [comment] 2021-03-24 13:30
That's a shame - are you using it to get the most similar text rendering to other text?

**Comment by TBProAudio** [comment] 2021-03-24 14:00
Hmm, I do not really know what the advantage is over platform text entry. It was just there :-)
If there is no real advantage on Win/Mac then we will skip it. We need to do it anyhow now, as it seems a little bit unstable...

**Comment by pressplay123** [comment] 2021-12-23 15:13
Any new insights on this issue? I'm having the exact same bug report (mac+vst+reaper: minus key not recognized). And as it is on a threshold level input (in dB), which in almost all cases expects negative values, it makes the feature unusable. Shall I go for the OS text entry field or is there a nice workaround for the iplug2 text entry equivalent?

**Comment by olilarkin** [comment] 2023-12-27 18:16
@TBProAudio @pressplay-music sorry for the multi-year silence on this. Hopefully #1042 works around the issue

**Comment by pressplay-music** [comment] 2023-12-27 18:49
> sorry for the multi-year silence on this. Hopefully #1042 works around the issue

Thanks for letting me know! I think I went with the native text entry, but I will reconsider that decision now.

**Comment by olilarkin** [comment] 2023-12-27 21:43
It seems this was indeed an issue with reaper, and should be fixed in the next version

**Comment by TBProAudio** [comment] 2023-12-28 16:23
Thanks Oli. What about VST3?

**Comment by olilarkin** [comment] 2023-12-28 16:59
The fix i have merged is for VST2 and VST3.

**Comment by olilarkin** [comment] 2023-12-28 16:59
The fix i have merged is for VST2 and VST3.

**Closed by olilarkin** 2023-12-28 16:59 UTC
Labels: bug, VST3, VST2, igraphics

**Comment by TBProAudio** [comment] 2023-12-29 07:29
Confirmed, thank you.
