### ISSUE TITLE
macOS Big Sur: SKIA CPU mode freezes UI

### ISSUE THREAD

**Issue by gvampgh** [iPlug2/iPlug2#649] opened 2020-11-14 05:54 UTC
After the update to macOS Big Sur, Skia CPU UI isn't responding anymore. The UI freezes and/or is extremely slow. Plug-Ins get unusable. METAL and GL2 modes seem to be ok.

**To Reproduce**
Newest IPlug2, newest IPLUG2_DEPS_MAC, IPlugControls example
change to IGRAPHICS_SKIA IGRAPHICS_CPU in xcconfig
add $(SKIA_LNK_FLAGS) to EXTRA_LNK_FLAGS

**Expected behaviour**
Normal performance

* What plug-in format does it relate to - All
* What platform does it relate to - macOS Big Sur
* What IGRAPHICS_BACKEND does it relate to: IGRAPHICS_SKIA CPU

**Additional context**
Debugger output throws this message endlessly:
...
IGraphics Skia CPU @ 60 FPS
2020-11-14 06:37:34.484059+0100 IPlugControls[3316:42866] [com.AcmeInc.app.IPlugControls] CGContextSaveGState: invalid context 0x6000037103c0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

This message comes from the IGraphicsSkia::EndFrame() method. The very first call of this method works, the first frame is shown, after this the error appears !

**Comment by gvampgh** [comment] 2020-11-14 06:05
The plugin suddenly begins to work properly, when I comment out this line in IGraphicsMac_view.mm. Seems the CGContextRef is changes for every frame now ?

```
// not called for layer backed views
- (void) drawRect: (NSRect) bounds
{
  #if !defined IGRAPHICS_GL && !defined IGRAPHICS_METAL
  if (mGraphics)
  {
//    if (!mGraphics->GetPlatformContext())
      mGraphics->SetPlatformContext([self getCGContextRef]);
```

**Comment by olilarkin** [comment] 2020-11-17 15:24
confirmed with BigSur on DTK

**Comment by hor-net** [comment] 2020-11-17 16:47
I can confirm this fixes everything, BigSur on MacBook Air 2020

**Comment by AlexHarker** [comment] 2020-11-20 16:15
A better fix would be to check if the context matches the currently stored context, because SetPlatformContext() could do quite a lot of work. I've done a quick check and it looks like we were only overriding that for Cairo (now deleted as a backend option), but I think the principle still stands.

**Comment by AlexHarker** [comment] 2020-11-20 16:18
Alternatively we could now make SetPlatformContext() non-virtual. I think we should also consider making mPlatformContext private and forcing access through GetPlatformContext (currently this is not the case).

I don't have a Big Sur install to test on, but I'm very interested to get this sorted soon, having just released with Skia CPU in some plugin builds.

**Comment by olilarkin** [comment] 2020-11-22 14:18
fixed on master

**Closed by olilarkin** 2020-11-22 14:18 UTC
