### ISSUE TITLE
iOS Examples crashing on load

### ISSUE THREAD

**Issue by AlexHarker** [iPlug2/iPlug2#981] opened 2023-06-18 15:01 UTC
See here:

https://iplug2.discourse.group/t/crashing-ios-examples/795/3

reproduced on iPad 9th generation emulator (on intel and ARM desktops) using iPlugEffect

**Comment by AlexHarker** [comment] 2023-06-18 15:08
The crash happens from here when the completion hander is called with an error (and then an error is caused that is unhandled):

https://github.com/iPlug2/iPlug2/blob/c259b038ca70a43266d388c56f837990e18a96be/IPlug/AUv3/iOSApp/IPlugAUPlayer.mm#L42

**Comment by AlexHarker** [comment] 2023-06-18 15:12
Actually the above is incorrect - the error returns as nil and then the following line crashes:

https://github.com/iPlug2/iPlug2/blob/c259b038ca70a43266d388c56f837990e18a96be/IPlug/AUv3/iOSApp/IPlugAUPlayer.mm#L90

Possibly this doesn't work on emulator? @olilarkin - do you know anything about this?

**Comment by olilarkin** [comment] 2023-06-18 15:23
IIRC, This is a problem on the simulator when the macOS audio device is not the built-in apple I/O. I get the crash when my babyface pro is the default interface, but not when built-in is the default. Here is a WIP fix I did at somepoint, i don't think it is correct:

```
diff --git forkSrcPrefix/IPlug/AUv3/iOSApp/IPlugAUPlayer.mm forkDstPrefix/IPlug/AUv3/iOSApp/IPlugAUPlayer.mm
index 159513a624a776092e3bdae25c2e1bc4c710c170..f88c2be0d8099a3bd5fd52182760783490981ac1 100644
--- forkSrcPrefix/IPlug/AUv3/iOSApp/IPlugAUPlayer.mm
+++ forkDstPrefix/IPlug/AUv3/iOSApp/IPlugAUPlayer.mm
@@ -62,7 +62,6 @@
   [session setCategory: AVAudioSessionCategoryPlayAndRecord error:&error];
 #endif
   
-  [session setPreferredSampleRate:iplug::DEFAULT_SAMPLE_RATE error:nil];
   [session setPreferredIOBufferDuration:128.0/iplug::DEFAULT_SAMPLE_RATE error:nil];
   AVAudioMixerNode* mainMixer = [audioEngine mainMixerNode];
   mainMixer.outputVolume = 1;
@@ -72,7 +71,8 @@
   AVAudioFormat* micInputFormat = [[audioEngine inputNode] inputFormatForBus:0];
   AVAudioFormat* pluginInputFormat = [avAudioUnit inputFormatForBus:0];
 #endif
-  
+  [session setPreferredSampleRate:micInputFormat.sampleRate error:nil];
+
   AVAudioFormat* pluginOutputFormat = [avAudioUnit outputFormatForBus:0];
 
   NSLog(@"Session SR: %i", int(session.sampleRate));
@@ -87,7 +87,7 @@
   
 #if PLUG_TYPE != 1
   if (pluginInputFormat != nil)
-    [audioEngine connect:audioEngine.inputNode to:avAudioUnit format: micInputFormat];
+    [audioEngine connect:audioEngine.inputNode to:avAudioUnit format: pluginInputFormat];
 #endif
   
   auto numOutputBuses = [avAudioUnit numberOfOutputs];
```

**Comment by olilarkin** [comment] 2023-06-18 15:23
duplicate of #944 i think

**Comment by AlexHarker** [comment] 2023-06-18 15:45
Confirmed as a duplicate - it so happened that I was on my RME when testing - so this is annoying, but not a showstopper...

**Comment by olilarkin** [comment] 2023-06-25 20:34
closing as duplicate

**Closed by olilarkin** 2023-06-25 20:34 UTC
Labels: bug, ios
